/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.presentation;

import main.domain.com.hidato.TipusAdjacencia;
import main.domain.com.hidato.TipusCella;
import main.domain.com.hidato.Usuari;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {
    CtrlVista cv;
    private static final int levelEasy = 1;
    private static final int levelInter = 2;
    private static final int levelHard = 3;
    private boolean esAuto = false;
    private boolean esCustom = false;
    private int randomType = (int) (Math.random() * 3) + 1;

    public VistaMenuPrincipal() {
        initComponents();
    }

    public VistaMenuPrincipal(CtrlVista v) {
        initComponents();
        cv = v;
        l_username.setText(cv.getCurrentUsername());
        l_username1.setText(cv.getCurrentUsername());
        l_password.setText(cv.getCurrentPassword());
        tipologia.addItem("Hexagon");
        tipologia.addItem("Quadrat");
        tipologia.addItem("Triangle");
        adjacencia.addItem("Costats");
        adjacencia.addItem("Costats i angles");
        adjacencia.setSelectedItem("Costat");
        tipologia.setSelectedItem("Hexagon");
        
        levelsButtons.add(easyButton);
        levelsButtons.add(interButton);
        levelsButtons.add(hardButton);
        tipologiaAuto.setEnabled(false);
        tipologiaAuto.addItem("Hexagon");
        tipologiaAuto.addItem("Quadrat");
        tipologiaAuto.addItem("Triangle");
        adjacenciaAuto.setEnabled(false);
        adjacenciaAuto.addItem("Costat");
        adjacenciaAuto.addItem("Costat i angles");
        adjacenciaAuto.setSelectedItem("Costat");
        tipologiaAuto.setSelectedItem("Hexagon");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelsButtons = new javax.swing.ButtonGroup();
        topBarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        b_userProfile = new javax.swing.JLabel();
        l_username = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        menuPrincipalPanel = new javax.swing.JPanel();
        b_play2 = new javax.swing.JButton();
        b_create1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        editPasswordPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        t_oldpass = new javax.swing.JPasswordField();
        t_newpass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t_rpass = new javax.swing.JPasswordField();
        b_cancel1 = new javax.swing.JButton();
        b_save1 = new javax.swing.JButton();
        deleteAccountPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t_password = new javax.swing.JPasswordField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l_username1 = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        b_delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        typeCreatePanel = new javax.swing.JPanel();
        b_autogenerar = new javax.swing.JButton();
        b_custom = new javax.swing.JButton();
        b_back = new javax.swing.JButton();
        b_custom1 = new javax.swing.JButton();
        createCustomPanel = new javax.swing.JPanel();
        tipologia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adjacencia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        altura = new javax.swing.JSpinner();
        amplada = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        b_backTypeCreate = new javax.swing.JButton();
        b_Create = new javax.swing.JButton();
        importPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        seleccioPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        b_back_menu = new javax.swing.JButton();
        resumePanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        quickLevelPanel = new javax.swing.JPanel();
        quickEasy = new javax.swing.JButton();
        quickInter = new javax.swing.JButton();
        quickHard = new javax.swing.JButton();
        b_back_menu1 = new javax.swing.JButton();
        createAutoPanel = new javax.swing.JPanel();
        b_backTypeCreate1 = new javax.swing.JButton();
        tipologiaCheckBox = new javax.swing.JCheckBox();
        adjacenciaCheckBox = new javax.swing.JCheckBox();
        adjacenciaAuto = new javax.swing.JComboBox<>();
        tipologiaAuto = new javax.swing.JComboBox<>();
        interButton = new javax.swing.JRadioButton();
        hardButton = new javax.swing.JRadioButton();
        easyButton = new javax.swing.JRadioButton();
        b_generate = new javax.swing.JButton();
        editUsernamePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        b_save = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        previewHidatoPanel = new javax.swing.JPanel();
        saveGame = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        saveGame1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hidato - Menu Principal");

        topBarPanel.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hidato");

        b_userProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/userIcon.png"))); // NOI18N
        b_userProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_userProfileMouseClicked(evt);
            }
        });

        l_username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        l_username.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                .addComponent(b_userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_username, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarPanelLayout.createSequentialGroup()
                        .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27))))
        );

        getContentPane().add(topBarPanel, java.awt.BorderLayout.PAGE_START);

        parentPanel.setBackground(new java.awt.Color(0, 153, 153));
        parentPanel.setForeground(new java.awt.Color(255, 255, 255));
        parentPanel.setLayout(new java.awt.CardLayout());

        menuPrincipalPanel.setBackground(new java.awt.Color(0, 153, 153));

        b_play2.setBackground(new java.awt.Color(204, 204, 204));
        b_play2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_play2.setText("Play");
        b_play2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_play2MouseClicked(evt);
            }
        });
        b_play2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_play2ActionPerformed(evt);
            }
        });

        b_create1.setBackground(new java.awt.Color(204, 204, 204));
        b_create1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_create1.setText("Create Hidato");
        b_create1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_create1MouseClicked(evt);
            }
        });
        b_create1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_create1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton5.setText("Ranking");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPrincipalPanelLayout = new javax.swing.GroupLayout(menuPrincipalPanel);
        menuPrincipalPanel.setLayout(menuPrincipalPanelLayout);
        menuPrincipalPanelLayout.setHorizontalGroup(
            menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalPanelLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_create1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_play2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        menuPrincipalPanelLayout.setVerticalGroup(
            menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalPanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(b_play2)
                .addGap(26, 26, 26)
                .addComponent(b_create1)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        parentPanel.add(menuPrincipalPanel, "card5");

        editPasswordPanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Old password");

        t_oldpass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        t_newpass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("New password");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Confirm new password");

        t_rpass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        b_cancel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_cancel1.setText("Cancel");
        b_cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_cancel1MouseClicked(evt);
            }
        });

        b_save1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_save1.setText("Save");
        b_save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_save1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editPasswordPanelLayout = new javax.swing.GroupLayout(editPasswordPanel);
        editPasswordPanel.setLayout(editPasswordPanelLayout);
        editPasswordPanelLayout.setHorizontalGroup(
            editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPasswordPanelLayout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editPasswordPanelLayout.createSequentialGroup()
                            .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14))
                            .addGap(71, 71, 71)
                            .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_oldpass, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(t_newpass)
                                .addComponent(t_rpass)))
                        .addGroup(editPasswordPanelLayout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(b_save1)
                            .addGap(18, 18, 18)
                            .addComponent(b_cancel1)))
                    .addContainerGap(234, Short.MAX_VALUE)))
        );
        editPasswordPanelLayout.setVerticalGroup(
            editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPasswordPanelLayout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPasswordPanelLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(33, 33, 33)
                            .addComponent(jLabel14)
                            .addGap(32, 32, 32)
                            .addComponent(jLabel15))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPasswordPanelLayout.createSequentialGroup()
                            .addComponent(t_oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(t_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(t_rpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(65, 65, 65)
                    .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_save1)
                        .addComponent(b_cancel1))
                    .addContainerGap(203, Short.MAX_VALUE)))
        );

        parentPanel.add(editPasswordPanel, "card9");

        deleteAccountPanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Enter your password to delete your account!");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Password:");

        t_password.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton9.setText("Delete account");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton10.setText("Cancel");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteAccountPanelLayout = new javax.swing.GroupLayout(deleteAccountPanel);
        deleteAccountPanel.setLayout(deleteAccountPanelLayout);
        deleteAccountPanelLayout.setHorizontalGroup(
            deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                .addGroup(deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteAccountPanelLayout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(jLabel17)
                            .addGap(53, 53, 53)
                            .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                            .addGap(238, 238, 238)
                            .addComponent(jLabel16)))
                    .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButton9)
                        .addGap(27, 27, 27)
                        .addComponent(jButton10)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        deleteAccountPanelLayout.setVerticalGroup(
            deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteAccountPanelLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(40, 40, 40)
                .addGroup(deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(97, 97, 97)
                .addGroup(deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(115, 115, 115))
        );

        parentPanel.add(deleteAccountPanel, "card10");

        profilePanel.setBackground(new java.awt.Color(0, 153, 153));

        jButton8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton8.setText("BACK");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Password");

        l_username1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        l_password.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        b_delete.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_delete.setText("DELETE ACCOUNT");
        b_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_deleteMouseClicked(evt);
            }
        });
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editIcon.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editIcon.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jSeparator2)))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(b_delete)
                        .addGap(39, 39, 39)
                        .addComponent(jButton8)))
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(profilePanelLayout.createSequentialGroup()
                    .addContainerGap(348, Short.MAX_VALUE)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(l_password, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(l_username1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(74, 74, 74)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(242, 242, 242)))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)))
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(b_delete))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(profilePanelLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(l_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(53, 53, 53)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(336, Short.MAX_VALUE)))
        );

        parentPanel.add(profilePanel, "card7");

        typeCreatePanel.setBackground(new java.awt.Color(0, 153, 153));

        b_autogenerar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_autogenerar.setText("Autogenerar");
        b_autogenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_autogenerarActionPerformed(evt);
            }
        });

        b_custom.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_custom.setText("Custom ");
        b_custom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_customActionPerformed(evt);
            }
        });

        b_back.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_back.setText("Back");
        b_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backActionPerformed(evt);
            }
        });

        b_custom1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_custom1.setText("Custom (Draw)");
        b_custom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_custom1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typeCreatePanelLayout = new javax.swing.GroupLayout(typeCreatePanel);
        typeCreatePanel.setLayout(typeCreatePanelLayout);
        typeCreatePanelLayout.setHorizontalGroup(
            typeCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeCreatePanelLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(typeCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_autogenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_custom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_custom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typeCreatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_back, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        typeCreatePanelLayout.setVerticalGroup(
            typeCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeCreatePanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(b_autogenerar)
                .addGap(70, 70, 70)
                .addComponent(b_custom)
                .addGap(63, 63, 63)
                .addComponent(b_custom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(b_back)
                .addGap(28, 28, 28))
        );

        parentPanel.add(typeCreatePanel, "card6");

        createCustomPanel.setBackground(new java.awt.Color(0, 153, 153));

        tipologia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Tipologia");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Adjacencia");

        adjacencia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Amplada");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Altuar");

        altura.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N

        amplada.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Create your hidato:");

        b_backTypeCreate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_backTypeCreate.setText("Back");
        b_backTypeCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backTypeCreateActionPerformed(evt);
            }
        });

        b_Create.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_Create.setText("Create");
        b_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCustomPanelLayout = new javax.swing.GroupLayout(createCustomPanel);
        createCustomPanel.setLayout(createCustomPanelLayout);
        createCustomPanelLayout.setHorizontalGroup(
            createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(b_backTypeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(createCustomPanelLayout.createSequentialGroup()
                .addGroup(createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createCustomPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amplada, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(adjacencia, 0, 154, Short.MAX_VALUE)
                            .addComponent(tipologia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(createCustomPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)))
                .addContainerGap(468, Short.MAX_VALUE))
        );
        createCustomPanelLayout.setVerticalGroup(
            createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomPanelLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(adjacencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amplada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_backTypeCreate)
                    .addComponent(b_Create))
                .addGap(33, 33, 33))
        );

        parentPanel.add(createCustomPanel, "card4");

        importPanel.setBackground(new java.awt.Color(0, 153, 153));

        jScrollPane1.setViewportView(jList1);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel20.setText("Select a Hidato:");

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setText("View Hidato");

        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setText("Enter the name of the hidato:");

        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton6.setText("Play");

        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout importPanelLayout = new javax.swing.GroupLayout(importPanel);
        importPanel.setLayout(importPanelLayout);
        importPanelLayout.setHorizontalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(importPanelLayout.createSequentialGroup()
                        .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(importPanelLayout.createSequentialGroup()
                        .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        importPanelLayout.setVerticalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        parentPanel.add(importPanel, "card13");

        seleccioPanel.setBackground(new java.awt.Color(0, 153, 153));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton2.setText("Quick game");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton3.setText("Import");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton4.setText("Resume");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        b_back_menu.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_back_menu.setText("Back");
        b_back_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_back_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seleccioPanelLayout = new javax.swing.GroupLayout(seleccioPanel);
        seleccioPanel.setLayout(seleccioPanelLayout);
        seleccioPanelLayout.setHorizontalGroup(
            seleccioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccioPanelLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addGroup(seleccioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(386, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seleccioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_back_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        seleccioPanelLayout.setVerticalGroup(
            seleccioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccioPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton2)
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addGap(33, 33, 33)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(b_back_menu)
                .addGap(38, 38, 38))
        );

        parentPanel.add(seleccioPanel, "card3");

        resumePanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel22.setText("Select a gameplay:");

        jScrollPane2.setViewportView(jList2);

        jButton11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton11.setText("Play");

        jButton12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resumePanelLayout = new javax.swing.GroupLayout(resumePanel);
        resumePanel.setLayout(resumePanelLayout);
        resumePanelLayout.setHorizontalGroup(
            resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resumePanelLayout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addGroup(resumePanelLayout.createSequentialGroup()
                            .addGap(470, 470, 470)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
        resumePanelLayout.setVerticalGroup(
            resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resumePanelLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel22)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(107, 107, 107)
                    .addGroup(resumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)))
        );

        parentPanel.add(resumePanel, "card14");

        quickLevelPanel.setBackground(new java.awt.Color(0, 153, 153));

        quickEasy.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        quickEasy.setText("Easy");
        quickEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickEasyActionPerformed(evt);
            }
        });

        quickInter.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        quickInter.setText("Intermediate");
        quickInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickInterActionPerformed(evt);
            }
        });

        quickHard.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        quickHard.setText("Hard");
        quickHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickHardActionPerformed(evt);
            }
        });

        b_back_menu1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_back_menu1.setText("Back");
        b_back_menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_back_menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quickLevelPanelLayout = new javax.swing.GroupLayout(quickLevelPanel);
        quickLevelPanel.setLayout(quickLevelPanelLayout);
        quickLevelPanelLayout.setHorizontalGroup(
            quickLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickLevelPanelLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(quickLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quickInter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quickEasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quickHard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(386, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quickLevelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_back_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        quickLevelPanelLayout.setVerticalGroup(
            quickLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickLevelPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(quickEasy)
                .addGap(55, 55, 55)
                .addComponent(quickInter)
                .addGap(70, 70, 70)
                .addComponent(quickHard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(b_back_menu1)
                .addGap(35, 35, 35))
        );

        parentPanel.add(quickLevelPanel, "card11");

        createAutoPanel.setBackground(new java.awt.Color(0, 153, 153));

        b_backTypeCreate1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_backTypeCreate1.setText("Back");
        b_backTypeCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backTypeCreate1ActionPerformed(evt);
            }
        });

        tipologiaCheckBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tipologiaCheckBox.setText("Tipologia (Optional)");
        tipologiaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipologiaCheckBoxActionPerformed(evt);
            }
        });

        adjacenciaCheckBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        adjacenciaCheckBox.setText("Adjacencia (Optional)");
        adjacenciaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjacenciaCheckBoxActionPerformed(evt);
            }
        });

        adjacenciaAuto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        tipologiaAuto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        interButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        interButton.setText("Intermediate");

        hardButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        hardButton.setText("Hard");

        easyButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        easyButton.setText("Easy");

        b_generate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_generate.setText("Generate");
        b_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_generateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAutoPanelLayout = new javax.swing.GroupLayout(createAutoPanel);
        createAutoPanel.setLayout(createAutoPanelLayout);
        createAutoPanelLayout.setHorizontalGroup(
            createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAutoPanelLayout.createSequentialGroup()
                .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createAutoPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(easyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(interButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adjacenciaCheckBox)
                            .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tipologiaAuto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adjacenciaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tipologiaCheckBox)))
                    .addGroup(createAutoPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_generate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(b_backTypeCreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        createAutoPanelLayout.setVerticalGroup(
            createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAutoPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createAutoPanelLayout.createSequentialGroup()
                        .addComponent(easyButton)
                        .addGap(31, 31, 31)
                        .addComponent(interButton)
                        .addGap(36, 36, 36)
                        .addComponent(hardButton))
                    .addGroup(createAutoPanelLayout.createSequentialGroup()
                        .addComponent(adjacenciaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adjacenciaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(tipologiaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipologiaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_backTypeCreate1)
                    .addComponent(b_generate))
                .addGap(28, 28, 28))
        );

        parentPanel.add(createAutoPanel, "card5");

        editUsernamePanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Old username");

        jTextField1.setBackground(new java.awt.Color(0, 153, 153));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField1.setBorder(null);

        jTextField2.setBackground(new java.awt.Color(0, 153, 153));
        jTextField2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField2.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("New username");

        b_save.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_save.setText("Save");
        b_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_saveMouseClicked(evt);
            }
        });

        b_cancel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_cancel.setText("Cancel");
        b_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editUsernamePanelLayout = new javax.swing.GroupLayout(editUsernamePanel);
        editUsernamePanel.setLayout(editUsernamePanelLayout);
        editUsernamePanelLayout.setHorizontalGroup(
            editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editUsernamePanelLayout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(58, 58, 58)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editUsernamePanelLayout.createSequentialGroup()
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editUsernamePanelLayout.createSequentialGroup()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(222, 222, 222)))))
            .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editUsernamePanelLayout.createSequentialGroup()
                    .addGap(266, 266, 266)
                    .addComponent(b_save)
                    .addGap(46, 46, 46)
                    .addComponent(b_cancel)
                    .addContainerGap(328, Short.MAX_VALUE)))
        );
        editUsernamePanelLayout.setVerticalGroup(
            editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUsernamePanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editUsernamePanelLayout.createSequentialGroup()
                    .addGap(278, 278, 278)
                    .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_save)
                        .addComponent(b_cancel))
                    .addContainerGap(216, Short.MAX_VALUE)))
        );

        parentPanel.add(editUsernamePanel, "card8");

        previewHidatoPanel.setBackground(new java.awt.Color(0, 153, 153));

        saveGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel18.setText("Generated Hidato:");

        saveGame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/repeatIcon.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anterior.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout previewHidatoPanelLayout = new javax.swing.GroupLayout(previewHidatoPanel);
        previewHidatoPanel.setLayout(previewHidatoPanelLayout);
        previewHidatoPanelLayout.setHorizontalGroup(
            previewHidatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewHidatoPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel18)
                .addContainerGap(537, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, previewHidatoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(27, 27, 27)
                .addComponent(saveGame)
                .addGap(27, 27, 27)
                .addComponent(saveGame1)
                .addGap(73, 73, 73))
        );
        previewHidatoPanelLayout.setVerticalGroup(
            previewHidatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewHidatoPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addGroup(previewHidatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveGame)
                    .addComponent(saveGame1)
                    .addComponent(jLabel19))
                .addGap(26, 26, 26))
        );

        parentPanel.add(previewHidatoPanel, "card12");

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(830, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_userProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_userProfileMouseClicked
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_userProfileMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(quickLevelPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b_play2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_play2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b_play2MouseClicked

    private void b_play2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_play2ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(seleccioPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_play2ActionPerformed

    private void b_create1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_create1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b_create1MouseClicked

    private void b_create1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_create1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(typeCreatePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_create1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        VistaRanking v = new VistaRanking(cv);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void b_customActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_customActionPerformed
        parentPanel.removeAll();
        parentPanel.add(createCustomPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_customActionPerformed

    private void b_autogenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_autogenerarActionPerformed
        parentPanel.removeAll();
        parentPanel.add(createAutoPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_autogenerarActionPerformed

    private void b_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backActionPerformed
        parentPanel.removeAll();
        parentPanel.add(menuPrincipalPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_backActionPerformed

    private void b_backTypeCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backTypeCreateActionPerformed
        parentPanel.removeAll();
        parentPanel.add(typeCreatePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_backTypeCreateActionPerformed

    private void b_back_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_back_menuActionPerformed
        parentPanel.removeAll();
        parentPanel.add(menuPrincipalPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_back_menuActionPerformed

    private void b_backTypeCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backTypeCreate1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(typeCreatePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_backTypeCreate1ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        parentPanel.removeAll();
        parentPanel.add(menuPrincipalPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton8MouseClicked

    private void b_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_deleteMouseClicked
        parentPanel.removeAll();
        parentPanel.add(deleteAccountPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_deleteMouseClicked

    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_deleteActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        parentPanel.removeAll();
        parentPanel.add(editPasswordPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        parentPanel.removeAll();
        parentPanel.add(editUsernamePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void b_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_saveMouseClicked
        String oldname = jTextField1.getText();
        String newname = jTextField2.getText();
        if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Enter your name");
        else {
            boolean successful = cv.editUsr(oldname, newname);
            if (successful){
                JOptionPane.showMessageDialog(null, "Your username has changed correctly");
                l_username.setText(cv.getCurrentUsername());
                l_username1.setText(cv.getCurrentUsername());
                parentPanel.removeAll();
                parentPanel.add(profilePanel);
                parentPanel.repaint();
                parentPanel.revalidate();
            }
            else {
                int input = JOptionPane.showOptionDialog(null, "The username exists or not correct", "Error message",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (input == JOptionPane.OK_OPTION) {
                    jTextField2.setText("");
                }
            }
        }
    }//GEN-LAST:event_b_saveMouseClicked

    private void b_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cancelMouseClicked
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_cancelMouseClicked

    private void b_cancel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cancel1MouseClicked
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_cancel1MouseClicked

    private void b_save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_save1MouseClicked
        String oldPassword = new String(t_oldpass.getPassword());
        String newPassword = new String(t_newpass.getPassword());
        String rnewPassword = new String(t_rpass.getPassword());
        if (oldPassword.length() == 0 || newPassword.length() == 0 || rnewPassword.length() == 0) 
            JOptionPane.showMessageDialog(null, "Enter your password please!");
        else {
            if (!newPassword.equals(rnewPassword)) {
                int input = JOptionPane.showOptionDialog(null, "Password not equals, try it again!", "Error message",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (input == JOptionPane.OK_OPTION) {
                    t_rpass.setText("");
                }
            }
            else {
                boolean successful = false;
                try {
                    successful = cv.changePass(oldPassword, rnewPassword);
                } catch (IOException ex) {
                    Logger.getLogger(VistaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (successful){
                    JOptionPane.showMessageDialog(null, "Your password has changed correctly!");
                    l_password.setText(cv.getCurrentPassword());
                    parentPanel.removeAll();
                    parentPanel.add(profilePanel);
                    parentPanel.repaint();
                    parentPanel.revalidate();
                    
                }
                else JOptionPane.showMessageDialog(null, "Your password hasn't changed correctly");
            }
        }
    }//GEN-LAST:event_b_save1MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        String pass1 = new String(t_password.getPassword());
        if (pass1.length() == 0) JOptionPane.showMessageDialog(null, "Enter your password please");
        else {
            boolean ok = cv.deleteUser(pass1);
            if (!ok) JOptionPane.showMessageDialog(null, "Wrong password!");
            else {
                JOptionPane.showMessageDialog(null, "Account deleted");
                Inici v = new Inici();
                v.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton10MouseClicked

    private void quickEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickEasyActionPerformed
        randomType = (int) (Math.random() * 3) + 1;
        System.out.println("HOLAAAAAAAAAAAAAAAAa" + " "  + randomType);
        VistaPartida v = new VistaPartida(cv, levelEasy, randomType);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quickEasyActionPerformed

    private void b_back_menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_back_menu1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(seleccioPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_back_menu1ActionPerformed

    private void quickInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickInterActionPerformed
        randomType = (int) (Math.random() * 3) + 1;
        VistaPartida v = new VistaPartida(cv, levelInter, randomType);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quickInterActionPerformed

    private void quickHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickHardActionPerformed
        randomType = (int) (Math.random() * 3) + 1;
        VistaPartida v = new VistaPartida(cv, levelHard, randomType);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quickHardActionPerformed

    private void b_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CreateActionPerformed
        esCustom = true;
       
        TipusCella tipusCella = stringToTipusCella((String)tipologia.getSelectedItem());
        TipusAdjacencia tipusAdjacencia = stringToTipusAdjacencia((String)tipologia.getSelectedItem());
        int alturaHidato = (int) altura.getValue();
        int ampladaHidato = (int) amplada.getValue();
        
        VistaCreateHidato v = new VistaCreateHidato(cv, tipusCella, tipusAdjacencia, alturaHidato, ampladaHidato);
        v.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_b_CreateActionPerformed

    private TipusCella stringToTipusCella(String selectedItem) {
        if (selectedItem.equalsIgnoreCase("HEXAGON")) return TipusCella.HEXAGON;
        if (selectedItem.equalsIgnoreCase("TRIANGLE")) return TipusCella.TRIANGLE;
        return TipusCella.QUADRAT;
	}
    
    private TipusAdjacencia stringToTipusAdjacencia(String selectedItem) {
        if (selectedItem.equalsIgnoreCase("COSTATS I ANGLES")) return TipusAdjacencia.COSTATSIANGLES;
        return TipusAdjacencia.COSTATS;
	}

	private void b_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_generateActionPerformed
        esAuto = true;
        parentPanel.removeAll();
        parentPanel.add(previewHidatoPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_generateActionPerformed

    private void adjacenciaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjacenciaCheckBoxActionPerformed
        if (adjacenciaCheckBox.isSelected()) adjacenciaAuto.setEnabled(true);
        else adjacenciaAuto.setEnabled(false);
    }//GEN-LAST:event_adjacenciaCheckBoxActionPerformed

    private void tipologiaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipologiaCheckBoxActionPerformed
        if (tipologiaCheckBox.isSelected()) tipologiaAuto.setEnabled(true);
        else tipologiaAuto.setEnabled(false);
    }//GEN-LAST:event_tipologiaCheckBoxActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if (esAuto) { 
            esAuto = false;
            parentPanel.removeAll();
            parentPanel.add(createAutoPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
        }
        if (esCustom) {
            esCustom = false;
            parentPanel.removeAll();
            parentPanel.add(createCustomPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
        }        
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(importPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(seleccioPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(seleccioPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(resumePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void b_custom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_custom1ActionPerformed
        //VistaCreateHidato v = new VistaCreateHidato(cv, levelEasy);
        //v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_custom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adjacencia;
    private javax.swing.JComboBox<String> adjacenciaAuto;
    private javax.swing.JCheckBox adjacenciaCheckBox;
    private javax.swing.JSpinner altura;
    private javax.swing.JSpinner amplada;
    private javax.swing.JButton b_Create;
    private javax.swing.JButton b_autogenerar;
    private javax.swing.JButton b_back;
    private javax.swing.JButton b_backTypeCreate;
    private javax.swing.JButton b_backTypeCreate1;
    private javax.swing.JButton b_back_menu;
    private javax.swing.JButton b_back_menu1;
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_cancel1;
    private javax.swing.JButton b_create1;
    private javax.swing.JButton b_custom;
    private javax.swing.JButton b_custom1;
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_generate;
    private javax.swing.JButton b_play2;
    private javax.swing.JButton b_save;
    private javax.swing.JButton b_save1;
    private javax.swing.JLabel b_userProfile;
    private javax.swing.JPanel createAutoPanel;
    private javax.swing.JPanel createCustomPanel;
    private javax.swing.JPanel deleteAccountPanel;
    private javax.swing.JRadioButton easyButton;
    private javax.swing.JPanel editPasswordPanel;
    private javax.swing.JPanel editUsernamePanel;
    private javax.swing.JRadioButton hardButton;
    private javax.swing.JPanel importPanel;
    private javax.swing.JRadioButton interButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_username;
    private javax.swing.JLabel l_username1;
    private javax.swing.ButtonGroup levelsButtons;
    private javax.swing.JPanel menuPrincipalPanel;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel previewHidatoPanel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton quickEasy;
    private javax.swing.JButton quickHard;
    private javax.swing.JButton quickInter;
    private javax.swing.JPanel quickLevelPanel;
    private javax.swing.JPanel resumePanel;
    private javax.swing.JLabel saveGame;
    private javax.swing.JLabel saveGame1;
    private javax.swing.JPanel seleccioPanel;
    private javax.swing.JPasswordField t_newpass;
    private javax.swing.JPasswordField t_oldpass;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JPasswordField t_rpass;
    private javax.swing.JComboBox<String> tipologia;
    private javax.swing.JComboBox<String> tipologiaAuto;
    private javax.swing.JCheckBox tipologiaCheckBox;
    private javax.swing.JPanel topBarPanel;
    private javax.swing.JPanel typeCreatePanel;
    // End of variables declaration//GEN-END:variables
}
