/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.presentation;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import main.domain.com.hidato.TipusAdjacencia;
import main.domain.com.hidato.TipusCella;
import main.domain.com.hidato.Usuari;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import main.domain.com.hidato.Hidato;
import main.domain.com.hidato.HidatoIO;

/**
 *
 * @author admin
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

  
    ControladorPresentacio controller = ControladorPresentacio.getInstance();
    private static final int levelEasy = 1;
    private static final int levelInter = 2;
    private static final int levelHard = 3;
    private boolean esAuto = false;
    private boolean esCustom = false;
    private int randomType = (int) (Math.random() * 3) + 1;
    
    private ControladorMenuPrincipal cmp;
    private ControladorPresentacio cp = ControladorPresentacio.getInstance();
    private static TipusCella tipusCella;
    private static TipusAdjacencia tipusAdjacencia;
    private static int[][] matriu;

    
    public VistaMenuPrincipal() {
        initComponents();
        cmp = new ControladorMenuPrincipal();

        l_username.setText(cp.getUsername());
        l_username1.setText(cp.getUsername());
        l_password.setText(cp.getPassword());
        tipologia.addItem("Hexagon");
        tipologia.addItem("Quadrat");
        tipologia.addItem("Triangle");
        adjacencia.addItem("Costats");
        adjacencia.addItem("Costats i angles");
        adjacencia.setSelectedItem("Costat");
        tipologia.setSelectedItem("Hexagon");

        levelsButtons.add(easyButton);
        levelsButtons.add(interButton);
        levelsButtons.add(hardButton);
        tipologiaAuto.setEnabled(false);
        tipologiaAuto.addItem("Hexagon");
        tipologiaAuto.addItem("Quadrat");
        tipologiaAuto.addItem("Triangle");
        adjacenciaAuto.setEnabled(false);
        adjacenciaAuto.addItem("Costat");
        adjacenciaAuto.addItem("Costat i angles");
        adjacenciaAuto.setSelectedItem("Costat");
        tipologiaAuto.setSelectedItem("Hexagon");
        showHidatoList();

    }

    private void showHidatoList() {
        DefaultListModel model = new DefaultListModel();
        String[] fitxers = cmp.getAllHidatoNames();

        for (int i = 0; i < fitxers.length; ++i) {
            model.addElement(fitxers[i]);
        }
        hidatoList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modgit ify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelsButtons = new javax.swing.ButtonGroup();
        topBarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        b_userProfile = new javax.swing.JLabel();
        l_username = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        menuPrincipalPanel = new javax.swing.JPanel();
        b_play = new javax.swing.JButton();
        b_create = new javax.swing.JButton();
        b_ranking = new javax.swing.JButton();
        editPasswordPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        t_oldpass = new javax.swing.JPasswordField();
        t_newpass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t_rpass = new javax.swing.JPasswordField();
        b_cancel1 = new javax.swing.JButton();
        b_save1 = new javax.swing.JButton();
        deleteAccountPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t_password = new javax.swing.JPasswordField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l_username1 = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        b_delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        b_signout = new javax.swing.JButton();
        typeCreatePanel = new javax.swing.JPanel();
        b_autogenerar = new javax.swing.JButton();
        b_fromtxt = new javax.swing.JButton();
        b_back = new javax.swing.JButton();
        b_custom = new javax.swing.JButton();
        createCustomPanel = new javax.swing.JPanel();
        tipologia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adjacencia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        altura = new javax.swing.JSpinner();
        amplada = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        b_backTypeCreate = new javax.swing.JButton();
        b_Create = new javax.swing.JButton();
        importPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hidatoList = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        viewHidato = new javax.swing.JButton();
        selectedHidato = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        seleccioPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        b_back_menu = new javax.swing.JButton();
        quickLevelPanel = new javax.swing.JPanel();
        quickEasy = new javax.swing.JButton();
        quickInter = new javax.swing.JButton();
        quickHard = new javax.swing.JButton();
        b_back_menu1 = new javax.swing.JButton();
        createAutoPanel = new javax.swing.JPanel();
        b_backTypeCreate1 = new javax.swing.JButton();
        tipologiaCheckBox = new javax.swing.JCheckBox();
        adjacenciaCheckBox = new javax.swing.JCheckBox();
        adjacenciaAuto = new javax.swing.JComboBox<>();
        tipologiaAuto = new javax.swing.JComboBox<>();
        interButton = new javax.swing.JRadioButton();
        hardButton = new javax.swing.JRadioButton();
        easyButton = new javax.swing.JRadioButton();
        b_generate = new javax.swing.JButton();
        editUsernamePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        oldName = new javax.swing.JTextField();
        newName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        b_save = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        previewHidatoPanel = new javax.swing.JPanel();
        saveGame = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        saveGame1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hidato - Menu Principal");
        setResizable(false);

        topBarPanel.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hidato");

        b_userProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/userIcon.png"))); // NOI18N
        b_userProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_userProfileMouseClicked(evt);
            }
        });

        l_username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        l_username.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(b_userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_username, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarPanelLayout.createSequentialGroup()
                        .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27))))
        );

        getContentPane().add(topBarPanel, java.awt.BorderLayout.PAGE_START);

        parentPanel.setBackground(new java.awt.Color(0, 153, 153));
        parentPanel.setForeground(new java.awt.Color(255, 255, 255));
        parentPanel.setLayout(new java.awt.CardLayout());

        menuPrincipalPanel.setBackground(new java.awt.Color(0, 153, 153));

        b_play.setBackground(new java.awt.Color(0, 204, 204));
        b_play.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_play.setText("Play");
        b_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_playMouseClicked(evt);
            }
        });
        b_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_playActionPerformed(evt);
            }
        });

        b_create.setBackground(new java.awt.Color(0, 204, 204));
        b_create.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_create.setText("Create Hidato");
        b_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_createMouseClicked(evt);
            }
        });
        b_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_createActionPerformed(evt);
            }
        });

        b_ranking.setBackground(new java.awt.Color(0, 204, 204));
        b_ranking.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_ranking.setText("Ranking");
        b_ranking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_rankingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPrincipalPanelLayout = new javax.swing.GroupLayout(menuPrincipalPanel);
        menuPrincipalPanel.setLayout(menuPrincipalPanelLayout);
        menuPrincipalPanelLayout.setHorizontalGroup(
            menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalPanelLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_ranking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(271, 271, 271))
        );
        menuPrincipalPanelLayout.setVerticalGroup(
            menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(b_play)
                .addGap(18, 18, 18)
                .addComponent(b_create)
                .addGap(18, 18, 18)
                .addComponent(b_ranking)
                .addContainerGap())
        );

        parentPanel.add(menuPrincipalPanel, "card5");

        editPasswordPanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Old password");

        t_oldpass.setBackground(new java.awt.Color(0, 153, 153));
        t_oldpass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        t_oldpass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        t_newpass.setBackground(new java.awt.Color(0, 153, 153));
        t_newpass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        t_newpass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("New password");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Confirm new password");

        t_rpass.setBackground(new java.awt.Color(0, 153, 153));
        t_rpass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        t_rpass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_rpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_rpassActionPerformed(evt);
            }
        });

        b_cancel1.setBackground(new java.awt.Color(0, 204, 204));
        b_cancel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_cancel1.setText("Cancel");
        b_cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_cancel1MouseClicked(evt);
            }
        });

        b_save1.setBackground(new java.awt.Color(0, 204, 204));
        b_save1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_save1.setText("Save");
        b_save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_save1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editPasswordPanelLayout = new javax.swing.GroupLayout(editPasswordPanel);
        editPasswordPanel.setLayout(editPasswordPanelLayout);
        editPasswordPanelLayout.setHorizontalGroup(
            editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPasswordPanelLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPasswordPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(108, 108, 108)
                        .addComponent(t_oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPasswordPanelLayout.createSequentialGroup()
                        .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_save1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPasswordPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(b_cancel1))
                            .addGroup(editPasswordPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(t_rpass, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPasswordPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(102, 102, 102)
                        .addComponent(t_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(175, 175, 175))
        );
        editPasswordPanelLayout.setVerticalGroup(
            editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPasswordPanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(editPasswordPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(t_oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(t_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(t_rpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_save1)
                    .addComponent(b_cancel1))
                .addGap(98, 98, 98))
        );

        parentPanel.add(editPasswordPanel, "card9");

        deleteAccountPanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setText("Enter your password to delete your account!");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Password:");

        t_password.setBackground(new java.awt.Color(0, 153, 153));
        t_password.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        t_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton9.setBackground(new java.awt.Color(0, 204, 204));
        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton9.setText("Delete account");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 204, 204));
        jButton10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton10.setText("Cancel");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteAccountPanelLayout = new javax.swing.GroupLayout(deleteAccountPanel);
        deleteAccountPanel.setLayout(deleteAccountPanelLayout);
        deleteAccountPanelLayout.setHorizontalGroup(
            deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                .addGroup(deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel16))
                    .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10))
                            .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(26, 26, 26)
                                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(190, 190, 190))
        );
        deleteAccountPanelLayout.setVerticalGroup(
            deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel16)
                .addGap(26, 26, 26)
                .addGroup(deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteAccountPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel17))
                    .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(deleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        parentPanel.add(deleteAccountPanel, "card10");

        profilePanel.setBackground(new java.awt.Color(0, 153, 153));

        jButton8.setBackground(new java.awt.Color(0, 204, 204));
        jButton8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton8.setText("BACK");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Password");

        l_username1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        l_username1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l_password.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        l_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        b_delete.setBackground(new java.awt.Color(0, 204, 204));
        b_delete.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_delete.setText("DELETE ACCOUNT");
        b_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_deleteMouseClicked(evt);
            }
        });
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editIcon.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editIcon.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        b_signout.setBackground(new java.awt.Color(0, 204, 204));
        b_signout.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_signout.setText("Sign out");
        b_signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_signoutMouseClicked(evt);
            }
        });
        b_signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_signoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(l_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))
                            .addComponent(l_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b_signout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(profilePanelLayout.createSequentialGroup()
                    .addContainerGap(476, Short.MAX_VALUE)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(242, 242, 242)))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(53, 53, 53)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(b_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_signout)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(profilePanelLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );

        parentPanel.add(profilePanel, "card7");

        typeCreatePanel.setBackground(new java.awt.Color(0, 153, 153));

        b_autogenerar.setBackground(new java.awt.Color(0, 204, 204));
        b_autogenerar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_autogenerar.setText("Autogenerar");
        b_autogenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_autogenerarActionPerformed(evt);
            }
        });

        b_fromtxt.setBackground(new java.awt.Color(0, 204, 204));
        b_fromtxt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_fromtxt.setText("from .txt ");
        b_fromtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fromtxtActionPerformed(evt);
            }
        });

        b_back.setBackground(new java.awt.Color(0, 204, 204));
        b_back.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_back.setText("Back");
        b_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backActionPerformed(evt);
            }
        });

        b_custom.setBackground(new java.awt.Color(0, 204, 204));
        b_custom.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_custom.setText("Custom ");
        b_custom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_customActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typeCreatePanelLayout = new javax.swing.GroupLayout(typeCreatePanel);
        typeCreatePanel.setLayout(typeCreatePanelLayout);
        typeCreatePanelLayout.setHorizontalGroup(
            typeCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typeCreatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_back, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(typeCreatePanelLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addGroup(typeCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_fromtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_custom, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_autogenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        typeCreatePanelLayout.setVerticalGroup(
            typeCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeCreatePanelLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(b_autogenerar)
                .addGap(28, 28, 28)
                .addComponent(b_custom)
                .addGap(31, 31, 31)
                .addComponent(b_fromtxt)
                .addGap(76, 76, 76)
                .addComponent(b_back)
                .addGap(19, 19, 19))
        );

        parentPanel.add(typeCreatePanel, "card6");

        createCustomPanel.setBackground(new java.awt.Color(0, 153, 153));

        tipologia.setBackground(new java.awt.Color(0, 153, 153));
        tipologia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Tipologia");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Adjacencia");

        adjacencia.setBackground(new java.awt.Color(0, 153, 153));
        adjacencia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Amplada");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Altuar");

        altura.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        altura.setModel(new javax.swing.SpinnerNumberModel(5, 3, 15, 1));

        amplada.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        amplada.setModel(new javax.swing.SpinnerNumberModel(5, 3, 15, 1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Create your hidato:");

        b_backTypeCreate.setBackground(new java.awt.Color(0, 204, 204));
        b_backTypeCreate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_backTypeCreate.setText("Back");
        b_backTypeCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backTypeCreateActionPerformed(evt);
            }
        });

        b_Create.setBackground(new java.awt.Color(0, 204, 204));
        b_Create.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_Create.setText("Create");
        b_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCustomPanelLayout = new javax.swing.GroupLayout(createCustomPanel);
        createCustomPanel.setLayout(createCustomPanelLayout);
        createCustomPanelLayout.setHorizontalGroup(
            createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomPanelLayout.createSequentialGroup()
                .addGroup(createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createCustomPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createCustomPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amplada, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(adjacencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipologia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(b_backTypeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        createCustomPanelLayout.setVerticalGroup(
            createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(adjacencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amplada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_backTypeCreate)
                    .addComponent(b_Create))
                .addGap(24, 24, 24))
        );

        parentPanel.add(createCustomPanel, "card4");

        importPanel.setBackground(new java.awt.Color(0, 153, 153));

        jScrollPane1.setViewportView(hidatoList);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel20.setText("Select a Hidato:");

        viewHidato.setBackground(new java.awt.Color(0, 204, 204));
        viewHidato.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        viewHidato.setText("View Hidato");
        viewHidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHidatoActionPerformed(evt);
            }
        });

        selectedHidato.setBackground(new java.awt.Color(0, 153, 153));
        selectedHidato.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        selectedHidato.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setText("Enter the name of the hidato:");

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton6.setText("Play");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 204, 204));
        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout importPanelLayout = new javax.swing.GroupLayout(importPanel);
        importPanel.setLayout(importPanelLayout);
        importPanelLayout.setHorizontalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(selectedHidato, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(importPanelLayout.createSequentialGroup()
                        .addComponent(viewHidato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        importPanelLayout.setVerticalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectedHidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHidato))
                .addGap(22, 22, 22))
        );

        parentPanel.add(importPanel, "card13");

        seleccioPanel.setBackground(new java.awt.Color(0, 153, 153));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton2.setText("Quick game");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton3.setText("Import");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton4.setText("Resume");
        jButton4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        b_back_menu.setBackground(new java.awt.Color(0, 204, 204));
        b_back_menu.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_back_menu.setText("Back");
        b_back_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_back_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seleccioPanelLayout = new javax.swing.GroupLayout(seleccioPanel);
        seleccioPanel.setLayout(seleccioPanelLayout);
        seleccioPanelLayout.setHorizontalGroup(
            seleccioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccioPanelLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(seleccioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(302, 302, 302))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seleccioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_back_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        seleccioPanelLayout.setVerticalGroup(
            seleccioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccioPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton2)
                .addGap(23, 23, 23)
                .addComponent(jButton3)
                .addGap(23, 23, 23)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(b_back_menu)
                .addGap(19, 19, 19))
        );

        parentPanel.add(seleccioPanel, "card3");

        quickLevelPanel.setBackground(new java.awt.Color(0, 153, 153));

        quickEasy.setBackground(new java.awt.Color(0, 204, 204));
        quickEasy.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        quickEasy.setText("Easy");
        quickEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickEasyActionPerformed(evt);
            }
        });

        quickInter.setBackground(new java.awt.Color(0, 204, 204));
        quickInter.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        quickInter.setText("Intermediate");
        quickInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickInterActionPerformed(evt);
            }
        });

        quickHard.setBackground(new java.awt.Color(0, 204, 204));
        quickHard.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        quickHard.setText("Hard");
        quickHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickHardActionPerformed(evt);
            }
        });

        b_back_menu1.setBackground(new java.awt.Color(0, 204, 204));
        b_back_menu1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_back_menu1.setText("Back");
        b_back_menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_back_menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quickLevelPanelLayout = new javax.swing.GroupLayout(quickLevelPanel);
        quickLevelPanel.setLayout(quickLevelPanelLayout);
        quickLevelPanelLayout.setHorizontalGroup(
            quickLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickLevelPanelLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(quickLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quickInter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quickEasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quickHard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quickLevelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_back_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        quickLevelPanelLayout.setVerticalGroup(
            quickLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickLevelPanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(quickEasy)
                .addGap(18, 18, 18)
                .addComponent(quickInter)
                .addGap(18, 18, 18)
                .addComponent(quickHard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(b_back_menu1)
                .addGap(35, 35, 35))
        );

        parentPanel.add(quickLevelPanel, "card11");

        createAutoPanel.setBackground(new java.awt.Color(0, 153, 153));

        b_backTypeCreate1.setBackground(new java.awt.Color(0, 204, 204));
        b_backTypeCreate1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_backTypeCreate1.setText("Back");
        b_backTypeCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backTypeCreate1ActionPerformed(evt);
            }
        });

        tipologiaCheckBox.setBackground(new java.awt.Color(0, 153, 153));
        tipologiaCheckBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tipologiaCheckBox.setText("Tipologia (Optional)");
        tipologiaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipologiaCheckBoxActionPerformed(evt);
            }
        });

        adjacenciaCheckBox.setBackground(new java.awt.Color(0, 153, 153));
        adjacenciaCheckBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        adjacenciaCheckBox.setText("Adjacencia (Optional)");
        adjacenciaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjacenciaCheckBoxActionPerformed(evt);
            }
        });

        adjacenciaAuto.setBackground(new java.awt.Color(0, 153, 153));
        adjacenciaAuto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        tipologiaAuto.setBackground(new java.awt.Color(0, 153, 153));
        tipologiaAuto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        interButton.setBackground(new java.awt.Color(0, 153, 153));
        interButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        interButton.setText("Intermediate");

        hardButton.setBackground(new java.awt.Color(0, 153, 153));
        hardButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        hardButton.setText("Hard");

        easyButton.setBackground(new java.awt.Color(0, 153, 153));
        easyButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        easyButton.setText("Easy");

        b_generate.setBackground(new java.awt.Color(0, 204, 204));
        b_generate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_generate.setText("Generate");
        b_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_generateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAutoPanelLayout = new javax.swing.GroupLayout(createAutoPanel);
        createAutoPanel.setLayout(createAutoPanelLayout);
        createAutoPanelLayout.setHorizontalGroup(
            createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAutoPanelLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAutoPanelLayout.createSequentialGroup()
                        .addComponent(b_generate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_backTypeCreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAutoPanelLayout.createSequentialGroup()
                        .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(easyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(interButton))
                        .addGap(61, 61, 61)
                        .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adjacenciaCheckBox)
                            .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tipologiaAuto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adjacenciaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tipologiaCheckBox))
                        .addGap(143, 143, 143))))
        );
        createAutoPanelLayout.setVerticalGroup(
            createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAutoPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAutoPanelLayout.createSequentialGroup()
                        .addComponent(adjacenciaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adjacenciaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(tipologiaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipologiaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createAutoPanelLayout.createSequentialGroup()
                        .addComponent(easyButton)
                        .addGap(31, 31, 31)
                        .addComponent(interButton)
                        .addGap(36, 36, 36)
                        .addComponent(hardButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(createAutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_generate)
                    .addComponent(b_backTypeCreate1))
                .addGap(18, 18, 18))
        );

        parentPanel.add(createAutoPanel, "card5");

        editUsernamePanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Old username");

        oldName.setBackground(new java.awt.Color(0, 153, 153));
        oldName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        oldName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        newName.setBackground(new java.awt.Color(0, 153, 153));
        newName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        newName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("New username");

        b_save.setBackground(new java.awt.Color(0, 204, 204));
        b_save.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_save.setText("Save");
        b_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_saveMouseClicked(evt);
            }
        });
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });

        b_cancel.setBackground(new java.awt.Color(0, 204, 204));
        b_cancel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        b_cancel.setText("Cancel");
        b_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editUsernamePanelLayout = new javax.swing.GroupLayout(editUsernamePanel);
        editUsernamePanel.setLayout(editUsernamePanelLayout);
        editUsernamePanelLayout.setHorizontalGroup(
            editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUsernamePanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_save)
                    .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)))
                .addGap(58, 58, 58)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancel))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        editUsernamePanelLayout.setVerticalGroup(
            editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUsernamePanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(73, 73, 73)
                .addGroup(editUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_save)
                    .addComponent(b_cancel))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        parentPanel.add(editUsernamePanel, "card8");

        previewHidatoPanel.setBackground(new java.awt.Color(0, 153, 153));

        saveGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel18.setText("Generated Hidato:");

        saveGame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/repeatIcon.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anterior.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout previewHidatoPanelLayout = new javax.swing.GroupLayout(previewHidatoPanel);
        previewHidatoPanel.setLayout(previewHidatoPanelLayout);
        previewHidatoPanelLayout.setHorizontalGroup(
            previewHidatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewHidatoPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel18)
                .addContainerGap(468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, previewHidatoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(27, 27, 27)
                .addComponent(saveGame)
                .addGap(27, 27, 27)
                .addComponent(saveGame1)
                .addGap(73, 73, 73))
        );
        previewHidatoPanelLayout.setVerticalGroup(
            previewHidatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewHidatoPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addGroup(previewHidatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveGame)
                    .addComponent(saveGame1)
                    .addComponent(jLabel19))
                .addGap(26, 26, 26))
        );

        parentPanel.add(previewHidatoPanel, "card12");

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_userProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_userProfileMouseClicked
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_userProfileMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(quickLevelPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_playMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b_playMouseClicked

    private void b_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_playActionPerformed
        parentPanel.removeAll();
        parentPanel.add(seleccioPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_playActionPerformed

    private void b_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_createMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b_createMouseClicked

    private void b_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_createActionPerformed
        parentPanel.removeAll();
        parentPanel.add(typeCreatePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_createActionPerformed

    private void b_rankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_rankingMouseClicked
        VistaRanking v = new VistaRanking();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_rankingMouseClicked

    private void b_fromtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fromtxtActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        if(archivo != null){
            String ruta = archivo.getAbsolutePath();
            System.out.println(ruta);
            try {
				controller.importarHidatotxt(ruta);
            }catch (Exception e) {
				// TODO Auto-generated catch block
            	JOptionPane.showMessageDialog(null, "hi ha hagut un error: " +e.getMessage());
			}
        }
    }//GEN-LAST:event_b_fromtxtActionPerformed

    private void b_autogenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_autogenerarActionPerformed
        parentPanel.removeAll();
        parentPanel.add(createAutoPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_autogenerarActionPerformed

    private void b_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backActionPerformed
        parentPanel.removeAll();
        parentPanel.add(menuPrincipalPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_backActionPerformed

    private void b_backTypeCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backTypeCreateActionPerformed
        parentPanel.removeAll();
        parentPanel.add(typeCreatePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_backTypeCreateActionPerformed

    private void b_back_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_back_menuActionPerformed
        parentPanel.removeAll();
        parentPanel.add(menuPrincipalPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_back_menuActionPerformed

    private void b_backTypeCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backTypeCreate1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(typeCreatePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_backTypeCreate1ActionPerformed

    private void b_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_saveMouseClicked
        String oldname = oldName.getText();
        String newname = newName.getText();
        if (oldName.getText().isEmpty() || newName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter your name");
        } else {
            boolean successful = cp.editUseranme(oldname, newname);
            if (successful) {
                JOptionPane.showMessageDialog(null, "Your username has changed correctly");
                l_username.setText(cp.getUsername());
                l_username1.setText(cp.getUsername());
                oldName.setText("");
                newName.setText("");
                parentPanel.removeAll();
                parentPanel.add(profilePanel);
                parentPanel.repaint();
                parentPanel.revalidate();
            } else {
                int input = JOptionPane.showOptionDialog(null, "Old username is not correct or the username not exisits in the DB", "Error message",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (input == JOptionPane.OK_OPTION) {
                    newName.setText("");
                }
            }
        }
    }//GEN-LAST:event_b_saveMouseClicked

    private void b_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cancelMouseClicked
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_cancelMouseClicked

    private void b_cancel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cancel1MouseClicked
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_cancel1MouseClicked

    private void b_save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_save1MouseClicked
        String oldPassword = new String(t_oldpass.getPassword());
        String newPassword = new String(t_newpass.getPassword());
        String rnewPassword = new String(t_rpass.getPassword());
        if (oldPassword.length() == 0 || newPassword.length() == 0 || rnewPassword.length() == 0) {
            JOptionPane.showMessageDialog(null, "Enter your password please!");
        } else {
            if (!newPassword.equals(rnewPassword)) {
                int input = JOptionPane.showOptionDialog(null, "Password not equals, try it again!", "Error message",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (input == JOptionPane.OK_OPTION) {
                    t_rpass.setText("");
                }
            } else {
                boolean successful = false;
                try {
                    successful = cp.changePass(oldPassword, rnewPassword);
                } catch (IOException ex) {
                    Logger.getLogger(VistaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (successful) {
                    JOptionPane.showMessageDialog(null, "Your password has changed correctly!");
                    l_password.setText(cp.getPassword());
                    t_oldpass.setText("");
                    t_newpass.setText("");
                    t_rpass.setText("");
                    parentPanel.removeAll();
                    parentPanel.add(profilePanel);
                    parentPanel.repaint();
                    parentPanel.revalidate();

                } else {
                    JOptionPane.showMessageDialog(null, "Your password hasn't changed correctly");
                }
            }
        }
    }//GEN-LAST:event_b_save1MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        String pass1 = new String(t_password.getPassword());
        if (pass1.length() == 0) {
            JOptionPane.showMessageDialog(null, "Enter your password please");
        } else {
            boolean ok = cp.deleteUser(pass1);
            if (!ok) {
                JOptionPane.showMessageDialog(null, "Wrong password!");
            } else {
                JOptionPane.showMessageDialog(null, "Account deleted");
                Inici v = new Inici();
                v.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton10MouseClicked

    private void quickEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickEasyActionPerformed
        randomType = (int) (Math.random() * 3) + 1;
        VistaPartida v = new VistaPartida(levelEasy, randomType, cp.getUsername());
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quickEasyActionPerformed

    private void b_back_menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_back_menu1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(seleccioPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_back_menu1ActionPerformed

    private void quickInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickInterActionPerformed
        randomType = (int) (Math.random() * 3) + 1;
        VistaPartida v = new VistaPartida(levelInter, randomType, cp.getUsername());
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quickInterActionPerformed

    private void quickHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickHardActionPerformed
        randomType = (int) (Math.random() * 3) + 1;
        VistaPartida v = new VistaPartida(levelHard, randomType, cp.getUsername());
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quickHardActionPerformed

    private void b_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CreateActionPerformed
        esCustom = true;
        TipusCella tipusCella = stringToTipusCella((String)tipologia.getSelectedItem());
        TipusAdjacencia tipusAdjacencia = stringToTipusAdjacencia((String)adjacencia.getSelectedItem());
        int alturaHidato = (int) altura.getValue();
        int ampladaHidato = (int) amplada.getValue();
        
        if (!compatibles(tipusCella, tipusAdjacencia)) JOptionPane.showMessageDialog(null, "El tipus de cella i el tipus d'adjacencia no son compatibles");
        else {
        	VistaCreateHidato v = new VistaCreateHidato(tipusCella, tipusAdjacencia, alturaHidato, ampladaHidato);
            v.setVisible(true);
            this.dispose();
        }  
    }//GEN-LAST:event_b_CreateActionPerformed

    private boolean compatibles(TipusCella tipusCella, TipusAdjacencia tipusAdjacencia) {
    	if (tipusCella == TipusCella.QUADRAT) return true;
    	else return (tipusAdjacencia == TipusAdjacencia.COSTATS);
    }
    
    private TipusCella stringToTipusCella(String selectedItem) {
        if (selectedItem.equalsIgnoreCase("HEXAGON")) return TipusCella.HEXAGON;
        if (selectedItem.equalsIgnoreCase("TRIANGLE")) return TipusCella.TRIANGLE;
        return TipusCella.QUADRAT;
	}
    
    private TipusAdjacencia stringToTipusAdjacencia(String selectedItem) {
        if (selectedItem.equalsIgnoreCase("COSTATS I ANGLES")) return TipusAdjacencia.COSTATSIANGLES;
        return TipusAdjacencia.COSTATS;
	}

	private void b_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_generateActionPerformed
        esAuto = true;
        parentPanel.removeAll();
        parentPanel.add(previewHidatoPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_generateActionPerformed

    private void adjacenciaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjacenciaCheckBoxActionPerformed
        if (adjacenciaCheckBox.isSelected()) {
            adjacenciaAuto.setEnabled(true);
        } else {
            adjacenciaAuto.setEnabled(false);
        }
    }//GEN-LAST:event_adjacenciaCheckBoxActionPerformed

    private void tipologiaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipologiaCheckBoxActionPerformed
        if (tipologiaCheckBox.isSelected()) {
            tipologiaAuto.setEnabled(true);
        } else {
            tipologiaAuto.setEnabled(false);
        }
    }//GEN-LAST:event_tipologiaCheckBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(importPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(seleccioPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_saveActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_jButton4ActionPerformed
        if (controller.cargarPartidaGuardada()) this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void b_cpstom1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //VistaCreateHidato v = new VistaCreateHidato(cp, levelEasy);
        //v.setVisible(true);
    }
  
    private void jButton4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4AncestorAdded

    private void t_rpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_rpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_rpassActionPerformed

    private void b_signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_signoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_signoutActionPerformed

    private void b_signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_signoutMouseClicked
        Inici v = new Inici();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_signoutMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        parentPanel.removeAll();
        parentPanel.add(editUsernamePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        parentPanel.removeAll();
        parentPanel.add(editPasswordPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_deleteActionPerformed

    private void b_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_deleteMouseClicked
        parentPanel.removeAll();
        parentPanel.add(deleteAccountPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_deleteMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        parentPanel.removeAll();
        parentPanel.add(menuPrincipalPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if (esAuto) {
            esAuto = false;
            parentPanel.removeAll();
            parentPanel.add(createAutoPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
        }
        if (esCustom) {
            esCustom = false;
            parentPanel.removeAll();
            parentPanel.add(createCustomPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(seleccioPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void viewHidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHidatoActionPerformed
        String nomHidato = selectedHidato.getText();
        System.out.println("Estic llegint: " + nomHidato);
        try {
            tipusCella = cmp.getTipusCellaHidatoSeleccionat(nomHidato);
       
            tipusAdjacencia = cmp.getTipusAdjacenciaHidatoSeleccionat(nomHidato);
        
            matriu = cmp.getMatriuHidatoSeleccionat(nomHidato);
            System.out.println(tipusCella);
            System.out.println(tipusAdjacencia);
            HidatoIO.writeHidatoMatrixToOutput(matriu);
            
        } catch (FileNotFoundException ex) {
            int input = JOptionPane.showOptionDialog(null, "Hidato with name " + selectedHidato.getText() + " not exists!", "Error message",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (input == JOptionPane.OK_OPTION) {
                    selectedHidato.setText("");
                }
        } catch (Exception ex) {
            Logger.getLogger(VistaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_viewHidatoActionPerformed

    private void b_customActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_customActionPerformed
       parentPanel.removeAll();
        parentPanel.add(createCustomPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_b_customActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    	System.out.println("play importat");

    	String nomHidato = selectedHidato.getText();
    	
    	try {
			if (controller.jugarPartidaImportada(nomHidato)) this.dispose();
    	} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Hi ha hagut un problema per cargar l'hidato seleccionat: " + e.getMessage());
			e.printStackTrace();
		}

    	
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adjacencia;
    private javax.swing.JComboBox<String> adjacenciaAuto;
    private javax.swing.JCheckBox adjacenciaCheckBox;
    private javax.swing.JSpinner altura;
    private javax.swing.JSpinner amplada;
    private javax.swing.JButton b_Create;
    private javax.swing.JButton b_autogenerar;
    private javax.swing.JButton b_back;
    private javax.swing.JButton b_backTypeCreate;
    private javax.swing.JButton b_backTypeCreate1;
    private javax.swing.JButton b_back_menu;
    private javax.swing.JButton b_back_menu1;
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_cancel1;
    private javax.swing.JButton b_create;
    private javax.swing.JButton b_custom;
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_fromtxt;
    private javax.swing.JButton b_generate;
    private javax.swing.JButton b_play;
    private javax.swing.JButton b_ranking;
    private javax.swing.JButton b_save;
    private javax.swing.JButton b_save1;
    private javax.swing.JButton b_signout;
    private javax.swing.JLabel b_userProfile;
    private javax.swing.JPanel createAutoPanel;
    private javax.swing.JPanel createCustomPanel;
    private javax.swing.JPanel deleteAccountPanel;
    private javax.swing.JRadioButton easyButton;
    private javax.swing.JPanel editPasswordPanel;
    private javax.swing.JPanel editUsernamePanel;
    private javax.swing.JRadioButton hardButton;
    private javax.swing.JList<String> hidatoList;
    private javax.swing.JPanel importPanel;
    private javax.swing.JRadioButton interButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_username;
    private javax.swing.JLabel l_username1;
    private javax.swing.ButtonGroup levelsButtons;
    private javax.swing.JPanel menuPrincipalPanel;
    private javax.swing.JTextField newName;
    private javax.swing.JTextField oldName;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel previewHidatoPanel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton quickEasy;
    private javax.swing.JButton quickHard;
    private javax.swing.JButton quickInter;
    private javax.swing.JPanel quickLevelPanel;
    private javax.swing.JLabel saveGame;
    private javax.swing.JLabel saveGame1;
    private javax.swing.JPanel seleccioPanel;
    private javax.swing.JTextField selectedHidato;
    private javax.swing.JPasswordField t_newpass;
    private javax.swing.JPasswordField t_oldpass;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JPasswordField t_rpass;
    private javax.swing.JComboBox<String> tipologia;
    private javax.swing.JComboBox<String> tipologiaAuto;
    private javax.swing.JCheckBox tipologiaCheckBox;
    private javax.swing.JPanel topBarPanel;
    private javax.swing.JPanel typeCreatePanel;
    private javax.swing.JButton viewHidato;
    // End of variables declaration//GEN-END:variables
}
