/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.presentation;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.domain.com.hidato.Usuari;

/**
 *
 * @author admin
 */
public class VistaRegistrar extends javax.swing.JFrame {

    ControladorPresentacio cp = ControladorPresentacio.getInstance();
    /**
     * Creates new form VistaRegistrar
     */
    public VistaRegistrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        okRegistrar = new javax.swing.JButton();
        tf_password = new javax.swing.JPasswordField();
        tf_rpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        okRegistrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hidato - Register");
        setBackground(new java.awt.Color(36, 67, 65));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(36, 67, 65));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");

        tf_username.setBackground(new java.awt.Color(36, 67, 65));
        tf_username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tf_username.setForeground(new java.awt.Color(255, 255, 255));
        tf_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_username.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Repeat password:");

        okRegistrar.setBackground(new java.awt.Color(0, 204, 204));
        okRegistrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        okRegistrar.setText("Create");
        okRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okRegistrarMouseClicked(evt);
            }
        });
        okRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okRegistrarActionPerformed(evt);
            }
        });

        tf_password.setBackground(new java.awt.Color(36, 67, 65));
        tf_password.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tf_password.setForeground(new java.awt.Color(255, 255, 255));
        tf_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_password.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        tf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passwordActionPerformed(evt);
            }
        });

        tf_rpassword.setBackground(new java.awt.Color(36, 67, 65));
        tf_rpassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tf_rpassword.setForeground(new java.awt.Color(255, 255, 255));
        tf_rpassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_rpassword.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Register");

        okRegistrar1.setBackground(new java.awt.Color(0, 204, 204));
        okRegistrar1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        okRegistrar1.setText("Back");
        okRegistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okRegistrar1MouseClicked(evt);
            }
        });
        okRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okRegistrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(okRegistrar)
                        .addGap(26, 26, 26)
                        .addComponent(okRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_rpassword)
                                .addGap(6, 6, 6))
                            .addComponent(tf_password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 78, Short.MAX_VALUE)))
                        .addGap(155, 155, 155))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_rpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okRegistrar)
                    .addComponent(okRegistrar1))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okRegistrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okRegistrar1ActionPerformed

    private void okRegistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okRegistrar1MouseClicked
        Inici v = new Inici();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_okRegistrar1MouseClicked

    private void tf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passwordActionPerformed

    private void okRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okRegistrarActionPerformed

    private void okRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okRegistrarMouseClicked
        String name, password, rPassword;
        name = tf_username.getText();
        password = new String(tf_password.getPassword());
        rPassword = new String(tf_rpassword.getPassword());
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter your name please!");
        }
        else if (password.length() == 0) {
            JOptionPane.showMessageDialog(null, "Enter your password please!");
        }
        else if (rPassword.length() == 0) {
            JOptionPane.showMessageDialog(null, "Enter again your password please!");
        }
        else if (password.equals(rPassword) && !password.isEmpty() && !rPassword.isEmpty()) {
            boolean successful = false;
            try {
                successful = cp.afegirUsuari(name, password);
            } catch (IOException ex) {
                Logger.getLogger(VistaRegistrar.class.getName()).log(Level.SEVERE, null, ex);
            }
          
            if (successful) {
                int input = JOptionPane.showOptionDialog(null, "Registration done!", "Message",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (input == JOptionPane.OK_OPTION) {
                    Inici v = new Inici();
                    v.setVisible(true);
                    this.dispose();
                }
                else {
                    Inici v = new Inici();
                    v.setVisible(true);
                    this.dispose();
                }

            } else {
                int input = JOptionPane.showOptionDialog(null, "The user is already exists, please try it again!", "Error message",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (input == JOptionPane.OK_OPTION) {
                    tf_username.setText("");
                    tf_password.setText("");
                    tf_rpassword.setText("");
                }

            }
        }
        else {
            int input = JOptionPane.showOptionDialog(null, "The passwords not match! Correct it.", "Error message",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

            if (input == JOptionPane.OK_OPTION) {
                tf_rpassword.setText("");
            }

        }
    }//GEN-LAST:event_okRegistrarMouseClicked

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton okRegistrar;
    private javax.swing.JButton okRegistrar1;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JPasswordField tf_rpassword;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
