/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.presentation;

import java.awt.Color;
import main.domain.com.hidato.Dificultat;
import main.domain.com.hidato.TipusAdjacencia;
import main.domain.com.hidato.TipusCella;

import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class VistaCreateHidato extends javax.swing.JFrame {

    private ControladorNavegacio controladorNavegacio = ControladorNavegacio.getInstance();
    private ControladorCreateHidato creacio;
    private int seguentMoviment = 1;
    private boolean inputsAllowed = true;


    /**
     * Creates new form NewJFrame
     */
    public VistaCreateHidato() {
        initComponents();
    }


    public VistaCreateHidato(TipusCella tipusCella, TipusAdjacencia tipusAdjacencia, int altura, int amplada) {
        initComponents();
        this.setTitle("Crear el hidato");
        creacio = new ControladorCreateHidato();
        creacio.setView(this);
        hidatoPanel = creacio.createHidato(tipusCella, tipusAdjacencia, altura , amplada);
        this.add(hidatoPanel);
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        actualNum = new javax.swing.JLabel();
        seguentNum = new javax.swing.JButton();
        antNum = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        guardarHidato = new javax.swing.JLabel();
        borrarNumPosats = new javax.swing.JLabel();
        cellaBuida = new javax.swing.JButton();
        cellaInvalida = new javax.swing.JButton();
        seleccionarNum = new javax.swing.JButton();
        instruccionIcon = new javax.swing.JLabel();
        hidatoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });

        controlPanel.setBackground(new java.awt.Color(204, 204, 204));

        actualNum.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        actualNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualNum.setText("1");
        actualNum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        seguentNum.setBackground(new java.awt.Color(255, 255, 255));
        seguentNum.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        seguentNum.setText(">");
        seguentNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seguentNumMousePressed(evt);
            }
        });

        antNum.setBackground(new java.awt.Color(255, 255, 255));
        antNum.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        antNum.setText("<");
        antNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                antNumMousePressed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anterior.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        guardarHidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N
        guardarHidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarHidatoMousePressed(evt);
            }
        });

        borrarNumPosats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/resetIcon.png"))); // NOI18N
        borrarNumPosats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarNumPosatsMouseClicked(evt);
            }
        });

        cellaBuida.setBackground(new java.awt.Color(255, 255, 255));
        cellaBuida.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        cellaBuida.setText("#");
        cellaBuida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cellaBuidaMousePressed(evt);
            }
        });

        cellaInvalida.setBackground(new java.awt.Color(255, 255, 255));
        cellaInvalida.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        cellaInvalida.setText("*");
        cellaInvalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cellaInvalidaMousePressed(evt);
            }
        });

        seleccionarNum.setBackground(new java.awt.Color(119, 196, 255));
        seleccionarNum.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        seleccionarNum.setText("Num");
        seleccionarNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccionarNumMousePressed(evt);
            }
        });

        instruccionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/help.png"))); // NOI18N
        instruccionIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instruccionIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(back)
                .addGap(18, 18, 18)
                .addComponent(borrarNumPosats)
                .addGap(18, 18, 18)
                .addComponent(guardarHidato)
                .addGap(188, 188, 188)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(antNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellaBuida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(actualNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seleccionarNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seguentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellaInvalida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(instruccionIcon)
                .addGap(26, 26, 26))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(antNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seguentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cellaBuida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cellaInvalida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seleccionarNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(back)
                    .addComponent(instruccionIcon))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(borrarNumPosats, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarHidato, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(46, 46, 46))
        );

        getContentPane().add(controlPanel, java.awt.BorderLayout.PAGE_END);

        hidatoPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout hidatoPanelLayout = new javax.swing.GroupLayout(hidatoPanel);
        hidatoPanel.setLayout(hidatoPanelLayout);
        hidatoPanelLayout.setHorizontalGroup(
            hidatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        hidatoPanelLayout.setVerticalGroup(
            hidatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        getContentPane().add(hidatoPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(886, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
    	if (inputsAllowed) {
	    	controladorNavegacio.openMenuView();
	        this.dispose();
    	}
    }//GEN-LAST:event_backMouseClicked

    private void borrarNumPosatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarNumPosatsMouseClicked
    	if (inputsAllowed) {
    		creacio.reset();
    	}
    }//GEN-LAST:event_borrarNumPosatsMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    	if (inputsAllowed) {
	    	if (seguentMoviment > creacio.getMinimMoviment()) {
	        	seguentMoviment = creacio.decrementarSeguentMoviment();
	            actualNum.setText(Integer.toString(seguentMoviment));
	        }
    	}
    }//GEN-LAST:event_jButton2MouseClicked
    
    private void seguentNumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seguentNumMousePressed
    	if (inputsAllowed) {
	    	if (seguentMoviment < creacio.getMaximMoviment()) {
	        	seguentMoviment = creacio.incrementarSeguentMoviment();
	        	actualNum.setText(Integer.toString(seguentMoviment));
	        }
    	}
    }//GEN-LAST:event_seguentNumMousePressed

    private void antNumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antNumMousePressed
    	if (inputsAllowed) {
	    	if (seguentMoviment > creacio.getMinimMoviment()) {
	        	seguentMoviment = creacio.decrementarSeguentMoviment();
	            actualNum.setText(Integer.toString(seguentMoviment));
	    	}	
    	}
    }//GEN-LAST:event_antNumMousePressed

    private void guardarHidatoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarHidatoMousePressed
    	if (inputsAllowed) {
    		inputsAllowed = false;
    		creacio.guardarHidato();
    	}
    }//GEN-LAST:event_guardarHidatoMousePressed

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
    	evt.consume(); //per evitar que es cridi dos cops a cada "tick" de la roda
    	if (inputsAllowed) {
    		if (evt.getWheelRotation() < 0) {
	        	if (seguentMoviment < creacio.getMaximMoviment()) {
	            	seguentMoviment = creacio.incrementarSeguentMoviment();
	            	actualNum.setText(Integer.toString(seguentMoviment));
	            }
	        }
	        else {
	        	if (seguentMoviment > creacio.getMinimMoviment()) {
	            	seguentMoviment = creacio.decrementarSeguentMoviment();
	                actualNum.setText(Integer.toString(seguentMoviment));
	            }
	        }
    	}
	        
    }//GEN-LAST:event_formMouseWheelMoved

    private void cellaBuidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cellaBuidaMousePressed
        if (inputsAllowed) {
        	creacio.setAlmoadilla();
            clearButtonsColor();
            cellaBuida.setBackground(new Color(119, 196, 255));
        }
    }//GEN-LAST:event_cellaBuidaMousePressed

    private void seleccionarNumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarNumMousePressed
    	if (inputsAllowed) {
	    	creacio.setNumero();
	        clearButtonsColor();
	        seleccionarNum.setBackground(new Color(119, 196, 255));
    	}
    }//GEN-LAST:event_seleccionarNumMousePressed

    private void cellaInvalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cellaInvalidaMousePressed
    	if (inputsAllowed) {
	    	creacio.setAsterisc();
	        clearButtonsColor();
	        cellaInvalida.setBackground(new Color(119, 196, 255));
    	}
       
    }//GEN-LAST:event_cellaInvalidaMousePressed

    private void instruccionIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instruccionIconMouseClicked
        controladorNavegacio.openInstruccions();
    }//GEN-LAST:event_instruccionIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCreateHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCreateHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCreateHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCreateHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCreateHidato().setVisible(true);
            }
        });
    }
    
    public void setSeguentMoviment(int seguentMoviment) {
    	if (seguentMoviment != 0) {
    		this.seguentMoviment = seguentMoviment;
            actualNum.setText(Integer.toString(seguentMoviment));
    	}
    	else {
    		actualNum.setText(" ");
    	}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualNum;
    private javax.swing.JButton antNum;
    private javax.swing.JLabel back;
    private javax.swing.JLabel borrarNumPosats;
    private javax.swing.JButton cellaBuida;
    private javax.swing.JButton cellaInvalida;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel guardarHidato;
    private javax.swing.JPanel hidatoPanel;
    private javax.swing.JLabel instruccionIcon;
    private javax.swing.JButton seguentNum;
    private javax.swing.JButton seleccionarNum;
    // End of variables declaration//GEN-END:variables

    private void clearButtonsColor() {
        seleccionarNum.setBackground(new Color(255,255,255));
        cellaInvalida.setBackground(new Color(255,255,255));
        cellaBuida.setBackground(new Color(255,255,255));

    }


	public void allowInputs() {
		inputsAllowed = true;
	}
    
}
